### ISSUE TITLE
Reconfigure failed with Connection refused

### ISSUE THREAD

**Issue by eduanb** [Graylog2/graylog2-cookbook#88]
Graylog does not start up after running:
sudo graylog-ctl reconfigure
I have tried to kill the etcd process which is holding the port but did not work. My guess is that the cookbook starts etcd before it should.
This is on the latest 2.2.3-1

```
Errno::ECONNREFUSED
 -------------------
Connection refused - connect(2) for "127.0.0.1" port 4001
```

[stacktrace.txt](https://github.com/Graylog2/graylog2-cookbook/files/901964/stacktrace.txt)

**Comment by mariussturm** [comment]
Hey,
please make sure that etcd is running and healthy before you run `graylog-ctl reconfigure`. You can check the logs in `/var/log/graylog/etcd`. Test the etcd service with `/opt/graylog/embedded/bin/etcdctl ls`.

Since this cookbook is not used on the appliances I am closing the issue. If you still have problems open a new one in `Graylog2/omnibus-graylog2`.

Thanks.
